/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Main;

import java.sql.Connection;
import java.sql.SQLException;
import util.ConnectionFactory;


public class Main {
    

    public static void main(String[] args) throws SQLException {
        
  
        
    System.out.println(new Main().getGreeting());

    Connection c = ConnectionFactory.getConnection();

    ConnectionFactory.closeConnection(c);
        }

    private boolean getGreeting() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
